services:
  - type: web
    name: aras-website
    env: node
    plan: free
    buildCommand: npm install -g pnpm@10.4.1 && pnpm config set node-linker hoisted && pnpm install --no-frozen-lockfile && pnpm run build && pnpm run db:push
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "mysql://3jRdVFcRmWbDn2r.root:LHI9g4jbAJ8eb4MX@gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/test"
      - key: JWT_SECRET
        generateValue: true
      - key: VITE_APP_ID
        value: aras-website-app
      - key: VITE_APP_TITLE
        value: ARAS Website
      - key: OAUTH_SERVER_URL
        value: "https://aras-website-58hq.onrender.com"
      - key: OWNER_OPEN_ID
        value: "admin-aras-2025"
      - key: CLOUDINARY_URL
        value: "cloudinary://265686958798149:VH8g6MA1-8E2rwVPO8y3S6qYMO0@dyqvxreo3"
